Fixes for usage with a Custom agent
ndbeals/winssh-pageant pull request #11
Opened 2021-07-07 12:08 UTC by gazzenger

The purpose of this pull request is to help fix a number of issues when using winssh-pageant with a custom SSH-Agent, such as creating an SSH-Agent using the *golang.org/x/crypto/ssh/agent* library.

## Custom Windows SSH-Agent Deadlock issue

I ran into an issue when using winssh-pageant with a custom SSH-Agent which abruptly would deadlock and crash winssh-pageant, I've detailed the issue at the following link, https://github.com/ndbeals/winssh-pageant/issues/10

The simple solution has been to replace,
https://github.com/ndbeals/winssh-pageant/blob/ff92839d336da9b51525796b80f51ed380176551/main.go#L30-L34
With,
https://github.com/ndbeals/winssh-pageant/blob/fd229a282869b09aabad860d21996bd72314e5b5/main.go#L31-L36

## Bufio Read Issue
A second issue relates to when a PuTTY client makes an initial list query to the SSH-Agent.
This starts with a write operation to the SSH-Agent https://github.com/ndbeals/winssh-pageant/blob/ff92839d336da9b51525796b80f51ed380176551/internal/sshagent/agent.go#L26

This is then followed by a read operation from the SSH-Agent, listing all the keys https://github.com/ndbeals/winssh-pageant/blob/ff92839d336da9b51525796b80f51ed380176551/internal/sshagent/agent.go#L34

The current code relies on all the key data being sent in a single read operation using bufio, however I ran into issues when using this with my custom SSH-Agent, as only the first 4 bytes of data was being returned (I later found out these 4 bytes are magic numbers - I think related to the named pipe).

I did some digging around, and according to the ssh-agent protocol specification ,
https://github.com/openssh/openssh-portable/blob/4e636cf201ce6e7e3b9088568218f9d4e2c51712/PROTOCOL.agent#L379-L387

So I've simply modified the code by breaking it into three distinct read functions, the code is
https://github.com/gazzenger/winssh-pageant/commit/c06f2e864e3088a0b46ff06ea6698a91c8d5cb18#diff-ee5318b37f84592ca501ef36813158b2096992143f93f41eec1b6a0f7205f12cR34-R74 
These three read functions,
- Read the magic number,
- Read the SSH2_AGENT_IDENTITIES_ANSWER,
- Read the number of keys, and
- Read all the key information in a single read operation
This has been tested and works with both my custom SSH-Agent as well as with Windows OpenSSH

Many thanks,
Gary

2021-07-08 12:52 UTC, ndbeals requested changes
Is there anything I overlooked?

2021-07-08 12:52 UTC, ndbeals commented on main.go
> +	msg := (*win.MSG)(unsafe.Pointer(win.GlobalAlloc(0, unsafe.Sizeof(win.MSG{}))))
For my own sake I'd like to better understand what this (and the following) line do. I'll start:

- `unsafe.Sizeof(win.MSG{})` ([reference](https://golang.org/pkg/unsafe/#Sizeof)) likely returns either 28 or 40 (depending on 32bit or 64bit OS) See https://pkg.go.dev/github.com/lxn/win#MSG
- that value is used in [`win.GlobalAlloc`](https://docs.microsoft.com/en-us/windows/win32/api/winbase/nf-winbase-globalalloc) to allocate a small chunk of bytes on the heap. (aside, I'm not worried about the overhead warnings on MSDN)
- `unsafe.Pointer` is making an unsafe pointer to that allocated heap memory
- `(*win.MSG)` is casting all of that into a pointer for a `win.MSG`.

Looking in the docs, `win.GlobalAlloc` returns a `HGLOBAL`, I'll suggest:

```suggestion
	hglobal := win.GlobalAlloc(0, unsafe.Sizeof(win.MSG{}))
	msg := (*win.MSG)(unsafe.Pointer(hglobal))
```

2021-07-08 12:52 UTC, ndbeals commented on main.go
> +	defer win.GlobalFree(win.HGLOBAL(unsafe.Pointer(msg)))
This frees the heap memory allocated on the above line at the end of this scope (defered).

Only suggestion here is to make use of the above suggested `hglobal`

```suggestion
	defer win.GlobalFree(hglobal)
```

2021-07-08 12:53 UTC, ndbeals commented
The bufio changes look good and they are well documented, nothing further is needed for those.

2021-07-08 12:56 UTC, ndbeals requested changes
Woops, mistakenly re-requested a review, kinda new to this, my bad.

2021-07-09 13:36 UTC, gazzenger commented
Hey thanks for looking over the code,

I found using either
```golang
runtime.LockOSThread()
``` 
or 
```golang
msg := (*win.MSG)(unsafe.Pointer(win.GlobalAlloc(0, unsafe.Sizeof(win.MSG{}))))
defer win.GlobalFree(win.HGLOBAL(unsafe.Pointer(msg)))
```
worked well to prevent the deadlock.

The deadlock issue is also resolved when I try running the code with both of these together.

Happy with both put both your suggestions
https://github.com/ndbeals/winssh-pageant/pull/11#discussion_r666158316
https://github.com/ndbeals/winssh-pageant/pull/11#discussion_r666162662


If you're happy I can put both in an update to the pull request
```golang
// main message loop
runtime.LockOSThread()
hglobal := win.GlobalAlloc(0, unsafe.Sizeof(win.MSG{}))
msg := (*win.MSG)(unsafe.Pointer(hglobal))
defer win.GlobalFree(hglobal)
for win.GetMessage(msg, 0, 0, 0) > 0 {
	win.TranslateMessage(msg)
	win.DispatchMessage(msg)
}
```

Let me know.

-Gary

2021-07-09 15:11 UTC, ndbeals commented
I've committed the suggestions I made, so if you'd like to add the `runtime.lockosthread` to the code in a further commit you author, please do so!

otherwise I'll wait a few hours and add it myself. Thanks again for all this work you've done :)

- Nathan

2021-07-09 15:14 UTC, ndbeals commented
Also, this is minor and optional, The user "gnamestnik" is responsible for authoring the first commit in this PR. I assume that's you, it's just the git history isn't pointing to the right email, so github doesn't know it's you "gazzenger"?

If that's the case, and _if you want to_ you can re-write the git history so it attributes the commits to the correct account.

2021-07-10 13:10 UTC, gazzenger commented
> Also, this is minor and optional, The user "gnamestnik" is responsible for authoring the first commit in this PR. I assume that's you, it's just the git history isn't pointing to the right email, so github doesn't know it's you "gazzenger"?
> 
> If that's the case, and _if you want to_ you can re-write the git history so it attributes the commits to the correct account.

Yep, I mistakenly didn't set the Git Config info correct.
I'll just leave it as is.

2021-07-13 18:26 UTC, merged

2021-07-13 18:26 UTC, ndbeals commented
Thanks again @gazzenger

2021-07-13 18:39 UTC, ndbeals commented
New version pushed, find it at https://github.com/ndbeals/winssh-pageant/releases/tag/v1.3